### ISSUE TITLE
Mates List, do not close

### ISSUE THREAD

**Issue by D3Portillo** [nodeschool/sanmiguel#11]
Este repo contiene el tracking de todos los miembros que se agreguen como organizadores o mentores

**Comment by D3Portillo** [comment]
@nodeschoolbot add member bryanlopezcodes

**Comment by riyadhalnur** [comment]
Here is what I can do for you:

* `help` - shows this help
* `create-repo {name}` - creates a nodeschool repo
* `add-user {username}` - adds a user to the `chapter-organizers` team and the org
* `create-team {team}` - creates a new team
* `add-team-user {team} {username}` - add a user to a specific team

**Comment by D3Portillo** [comment]
@nodeschoolbot help

**Comment by riyadhalnur** [comment]
Here is what I can do for you:

* `help` - shows this help
* `create-repo {name}` - creates a nodeschool repo
* `add-user {username}` - adds a user to the `chapter-organizers` team and the org
* `create-team {team}` - creates a new team
* `add-team-user {team} {username}` - add a user to a specific team

**Comment by D3Portillo** [comment]
@nodeschoolbot add-user bryanlopezcodes

**Comment by riyadhalnur** [comment]
I have added @bryanlopezcodes to the `chapter-organizers` team.

**Comment by D3Portillo** [comment]
@nodeschoolbot add-team-user sanmiguel bryanlopezcodes

**Comment by riyadhalnur** [comment]
I cannot find the team `sanmiguel`

**Comment by riyadhalnur** [comment]
I have invited @bryanlopezcodes to the `sanmiguel` team.

**Comment by D3Portillo** [comment]
Agreado @bryanlopezcodes :zap:

**Comment by moudev** [comment]
@nodeschoolbot add-team-user sanmiguel arnoldou

**Comment by riyadhalnur** [comment]
I cannot find the team `sanmiguel`

**Comment by riyadhalnur** [comment]
I have invited @arnoldou to the `sanmiguel` team.

**Comment by moudev** [comment]
@nodeschoolbot add-team-user sanmiguel F3rnand02

**Comment by riyadhalnur** [comment]
I cannot find the team `sanmiguel`

**Comment by riyadhalnur** [comment]
I have invited @F3rnand02 to the `sanmiguel` team.

**Comment by moudev** [comment]
@nodeschoolbot add-team-user sanmiguel PaulinoShy

**Comment by riyadhalnur** [comment]
I cannot find the team `sanmiguel`

**Comment by riyadhalnur** [comment]
I have invited @PaulinoShy to the `sanmiguel` team.

**Comment by moudev** [comment]
@nodeschoolbot add-team-user sanmiguel fernando9825

**Comment by riyadhalnur** [comment]
I cannot find the team `sanmiguel`

**Comment by riyadhalnur** [comment]
I have invited @fernando9825 to the `sanmiguel` team.
