### ISSUE TITLE
Quiero ser mentor

### ISSUE THREAD

**Issue by erjosara8916** [nodeschool/sanmiguel#4]

**Comment by D3Portillo** [comment]
[Contactame :tada: ](https://www.facebook.com/d3portillo) y visita injuve el siguiente sabádo para hacerte un test y poder ser mentor :100: :100: , te esperamos de 8.30 en adelante ;3

**Comment by D3Portillo** [comment]
[Tests](https://github.com/nodeschool/sanmiguel/blob/master/tests.md)

**Comment by erjosara8916** [comment]
Hasta ahora m fije del test aunque la verdad tras mandar el mensaje luego
pense q la verdad aprendí d forma práctica x lo q no creo q sea conveniente
ser mentor lo mejor creo q sera q solo siga aportando ideas

**Comment by erjosara8916** [comment]
No m deja enviar el código lo mandare mañana q m conecte con la pc a
internet xq estoy desde el teléfono

**Comment by D3Portillo** [comment]
hola muy buenas @erjosara8916 , claro que puedes unirtenos y aportar cada idea que gustes, contactanos en [pagina](https://www.facebook.com/nodeschoolsm/) , o en personal a mi [facebook](https://www.facebook.com/d3portillo)
