### ISSUE TITLE
Quiero ser miembro

### ISSUE THREAD

**Issue by Nrycord** [nodeschool/sanmiguel#5]
quiero ser miembro :)

**Comment by D3Portillo** [comment]
[Contactame :boom: :boom:](https://www.facebook.com/d3portillo) y asiste el siguiente sabádo Injuve de 8.30 a 11.30, te esparamos :tada: :tada:

**Comment by D3Portillo** [comment]
esperando tu asistencia :taco: :fire: :fire: :tada:
